version: 2

jobs:
  build:
    docker:
      - image: java:9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          docker build --pull -t docker-secor .
      - run: |
          export IMAGE_NAME="images.scrapinghub.com/docker-secor/${CIRCLE_BRANCH}"
          export IMAGE_TAG="${CIRCLE_SHA1:0:7}"
          docker login -u $DOCKER_USER -p $DOCKER_PASS images.scrapinghub.com
          docker tag docker-secor "${IMAGE_NAME}:${IMAGE_TAG}"
          docker tag docker-secor "${IMAGE_NAME}:latest"
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"
          docker push "${IMAGE_NAME}:latest"